name: 'Docker Build Image'
description: 'Build an docker image'
inputs:
  DOCKER_IMAGE:
    description: "Image name to build"
    required: true
  
  DOCKER_TAG:
    description: "Tag name to build"
    required: true
  
  context:
    description: "Path to the directory where the Dockerfile is located"
    default: "."
    required: true
  
  file:
    description: "Path to the Dockerfile"
    required: true
  
  Username:
    description: "Username for registry"
    required: true
  
  Password:
    description: "Password for registry"
    required: true    
  
  build-args:
    description: "Build args as json array"
    required: false

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set outputs
      shell: bash
      id: vars
      run: |
        echo "::set-output name=sha_short::${{ inputs.DOCKER_TAG }}"
        echo "::set-output name=DOCKER_IMAGE::${{ inputs.DOCKER_IMAGE }}"

    - name: Set up Docker Context for Buildx
      shell: bash
      id: buildx-context
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        endpoint: builders

    - name: Inspect builder
      shell: bash
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.Username }}
        password: ${{ inputs.Password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ steps.vars.outputs.DOCKER_IMAGE }}
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        pull: true
        build-args: |
          ${{ steps.vars.outputs.BUILD_ARGS }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        tags: |
          ${{ steps.vars.outputs.DOCKER_IMAGE }}:${{ steps.vars.outputs.sha_short }}
          ${{ steps.vars.outputs.DOCKER_IMAGE }}:latest
        labels: ${{ steps.meta.outputs.labels }}
